[colors]
# Jehuty Dark theme for WezTerm
# Usage: Add this to your wezterm.toml config or reference it as a color scheme

# The default text color
foreground = "#eef0f9"
# The default background color  
background = "#0d1117"

# Overrides the cell background color when the current cell is occupied by the cursor
cursor_bg = "#aeafad"
# Overrides the text color when the current cell is occupied by the cursor
cursor_fg = "#000000"
# Specifies the border color of the cursor when the cursor style is set to Block
cursor_border = "#aeafad"

# The color of the scrollbar "thumb"; the portion that represents the current viewport
scrollbar_thumb = "#545864"

# The color of the split lines between panes
split = "#21262d"

ansi = [
  "#0d1117", # black
  "#dc3657", # red  
  "#23d18b", # green
  "#ffc368", # yellow
  "#2b7eca", # blue
  "#ad5dca", # magenta
  "#24c0cf", # cyan
  "#eef0f9", # white
]

brights = [
  "#545864", # bright black
  "#f4587e", # bright red
  "#4bf3c8", # bright green  
  "#ffd493", # bright yellow
  "#54b9ff", # bright blue
  "#cc75f4", # bright magenta
  "#00daef", # bright cyan
  "#fafafa", # bright white
]

[colors.indexed]
# Arbitrary colors of the palette in the range from 16 to 255
16 = "#161b22"
17 = "#21262d"
18 = "#858b98"
19 = "#bfc1c9"
20 = "#acafff"

# Since: 20220319-142410-0fcdea07
# When the IME, a dead key or a leader key are being processed and are effectively
# holding input pending the result of input composition, change the cursor
# to this color to give a visual cue about the compose state.
compose_cursor = "#ffd493"

[colors.selection]
# The color of the background in the selection
background = "#ad5dca44"
# The foreground color of the selection
foreground = "#eef0f9"

[colors.copy_mode]
# The color of the active text in copy mode
active_highlight_bg = { Color = "#ffd493" }
# The color of the inactive text in copy mode  
inactive_highlight_bg = { Color = "#545864" }

[colors.quick_select]
# The color of the quick select highlight
label_bg = { Color = "#4bf3c8" }
label_fg = { Color = "#000000" }
match_bg = { Color = "#ffd493" }
match_fg = { Color = "#000000" }